'use client';
import Link from 'next/link';
import {useState,type ChangeEvent} from 'react';
import {Plus,Trash2,Upload,Waves,ArrowUpRight} from 'lucide-react';
import {Field} from './number-field';
import {NativeSelect} from './ui/native-select';
import {useSaved} from '@/lib/storage';
import {cashflow} from '@/lib/finance';
import {money} from '@/lib/projection';
import {frequencies,monthlyAmount,todayString,paydayPlan,parseCSV,recurringSuggestions,type FlowItem,type Frequency} from '@/lib/current';
const empty:FlowItem[]=[];
const accountDefault={balance:0,reserve:0,confirmed:false,asOf:''};
const kinds=['income','fixed','variable','saving'] as const;
const labels={income:'Take-home income',fixed:'Fixed bills',variable:'Flexible spending',saving:'Savings & investments'};
const hints={income:'What actually lands in your account, on your schedule.',fixed:'Rent, subscriptions, and other predictable bills.',variable:'Plan for groceries, utilities, and amounts that change.',saving:'Set money aside on a schedule or whenever a paycheck arrives.'};
const uid=()=>crypto.randomUUID?.()??Array.from(crypto.getRandomValues(new Uint32Array(4)),n=>n.toString(16)).join('-');
const displayDate=(date:string)=>new Date(date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'});
type Suggestion=ReturnType<typeof recurringSuggestions>[number];
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){return <label className="current-choice"><span>{label}</span><NativeSelect value={value} onChange={e=>onChange(e.target.value)}>{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</NativeSelect></label>}
export function Current(){
 const [items,setItems,ready,error]=useSaved<FlowItem[]>('current',empty);
 const [account,setAccount,,accountError]=useSaved('current-account',accountDefault);
 const [view,setView]=useState<'payday'|'monthly'>('payday');
 const [suggestions,setSuggestions]=useState<Suggestion[]>([]);
 const [selected,setSelected]=useState<string[]>([]);
 const [message,setMessage]=useState('');
 const [busy,setBusy]=useState(false);
 const today=todayString(),f=cashflow(items),plan=paydayPlan(items,today,account.balance,account.reserve);
 const income=items.filter(i=>i.kind==='income');
 const update=(id:string,patch:Partial<FlowItem>)=>setItems(prev=>prev.map(i=>i.id===id?{...i,...patch}:i));
 const add=(kind:FlowItem['kind'])=>setItems(prev=>[...prev,{id:uid(),name:kind==='income'?'Take-home pay':kind==='saving'?'Savings':'New category',amount:0,kind,frequency:'monthly',mode:'scheduled'}]);
 async function importFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;setMessage('');setSuggestions([]);setSelected([]);if(file.size>5*1024*1024){setMessage('Please choose a CSV smaller than 5 MB.');return}if(!file.name.toLowerCase().endsWith('.csv')){setMessage('Choose a transaction CSV exported from your bank. PDF and scanned statements are not supported yet.');return}setBusy(true);try{const transactions=parseCSV(await file.text());const found=recurringSuggestions(transactions);setSuggestions(found);setMessage(found.length?`${transactions.length} transactions read. Review ${found.length} possible recurring items below.`:`${transactions.length} transactions read, but no reliable recurring patterns found. Try several months of transactions, or add items manually.`)}catch(err){setMessage(err instanceof Error?err.message:'This file could not be read.')}finally{setBusy(false)}}
 function importSelected(){const chosen=suggestions.filter(s=>selected.includes(s.id));const duplicate=(s:FlowItem)=>items.some(i=>i.name.toLowerCase()===s.name.toLowerCase()&&i.kind===s.kind);const additions=chosen.filter(s=>!duplicate(s)).map(({count,reason,...item})=>({...item,id:uid()}));setItems(prev=>[...prev,...additions]);setSuggestions([]);setSelected([]);setMessage(`Added ${additions.length} recurring items. ${chosen.length-additions.length} existing items skipped. Check amounts, dates, and schedules below.`)}
 const hasPlan=account.confirmed&&account.asOf===today&&!!plan.next&&plan.undated.length===0;
 return <main id="main" className="tool-page current-page"><div className="tool-heading"><span className="eyebrow">YOUR MONEY, AT YOUR PACE</span><h1>Current<span>.</span></h1><p>Build your plan around the way you get paid.</p></div><p className="save-note" role="status">{error||accountError?'This browser could not save your changes. Keep this page open.':'Saved on this device · No account or bank connection'}</p>
 <div className="current-view" role="group" aria-label="Planning view"><button aria-pressed={view==='payday'} onClick={()=>setView('payday')}>Until next payday</button><button aria-pressed={view==='monthly'} onClick={()=>setView('monthly')}>Monthly overview</button></div>
 {view==='payday'?<section className="glass current-payday"><div><span className="eyebrow">ROOM TO BREATHE</span><h2>{plan.next?`Before ${displayDate(plan.next.date)}`:'Start with your next payday'}</h2><p>{plan.next?`${plan.next.name}: ${money(plan.next.amount)} expected ${displayDate(plan.next.date)}.`:'Add take-home income and its next payment date to see what needs covering before you get paid.'}</p><div className="current-available"><span>{hasPlan?(plan.available<0?'Planned shortfall':'Available after your plan'):'Complete your plan to see what’s available'}</span><strong>{hasPlan?money(plan.available):'—'}</strong></div><p className="help">{hasPlan?'Starting balance minus protected money and scheduled outflows before payday. Unplanned purchases still reduce what’s available.':'Enter a starting balance and dates for every item. Undated commitments could otherwise make this estimate too high.'}</p></div><div className="current-balance"><Field label="Checking balance at the start of today" value={account.balance} step={.01} suffix="$" onChange={balance=>setAccount({...account,balance,confirmed:true,asOf:today})}/><Field label="Keep untouched in checking" value={account.reserve} step={.01} suffix="$" onChange={reserve=>setAccount({...account,reserve})}/><label className="current-check"><input type="checkbox" checked={account.confirmed&&account.asOf===today} onChange={e=>setAccount({...account,confirmed:e.target.checked,asOf:today})}/> I’ve entered today’s starting balance</label><p className="help">Update this balance when you revisit. The protected amount stays in checking; it is not counted as a new savings contribution.</p></div></section>:<section className="glass current-payday"><div><span className="eyebrow">THE BIGGER PICTURE</span><h2>Your average month, in motion.</h2><p>Weekly pay × 52 ÷ 12. Biweekly pay × 26 ÷ 12. Twice-monthly pay × 2. These averages help compare different schedules.</p></div><div className="current-available"><span>{f.remaining<0?'Average monthly shortfall':'Average monthly remaining'}</span><strong>{money(f.remaining)}</strong><p className="help">One-time items appear in the dated plan, not recurring monthly averages.</p></div></section>}
 <div className="metric-grid">{(view==='monthly'?[["Average income",f.income],["Average spending",f.spending],["Saving & investing",f.saving],["Remaining",f.remaining]]:[["Starting balance",account.balance],["Protected in checking",account.reserve],[plan.next?'Planned before payday':'Planned next 14 days',plan.outflows],['Monthly savings average',f.saving]]).map(([label,value])=><div className="glass metric" key={label}><span>{label}</span><strong>{money(Number(value))}</strong></div>)}</div>
 {view==='payday'&&<section className="glass current-agenda"><div className="panel-heading"><h2>Coming up</h2><span>{displayDate(today)} – {displayDate(plan.end)}</span></div>{plan.undated.length>0&&<p className="notice">{plan.undated.length} item(s) need a valid schedule or a linked paycheck before your plan is complete.</p>}{plan.events.filter(e=>e.kind!=='income').length?<ul>{plan.events.filter(e=>e.kind!=='income').map(e=><li key={e.id+e.date}><time dateTime={e.date}>{displayDate(e.date)}</time><span>{e.name}<small>{labels[e.kind]}</small></span><strong>{money(e.amount)}</strong></li>)}</ul>:<p className="help">No dated outflows in this window. Add your bills, spending allowances, and savings below.</p>}<p className="fine">Payday itself is the next planning window. Income expected today is excluded from available money until you receive it and update your balance. Treat flexible spending entries as dated allowances.</p></section>}
 <section className="glass current-import"><div><Upload size={23}/><h2>A head start from your statement.</h2><p>Import a bank transaction CSV to find possible recurring paychecks and bills. Several months work best. You choose what to add.</p><p className="help">Processed in your browser. The file and transaction history are not uploaded or saved. Only confirmed planning items stay on this device.</p></div><label className="button glass-button">{busy?'Reading transactions…':'Choose transaction CSV'}<input aria-label="Import transaction CSV" type="file" accept=".csv,text/csv" disabled={busy||!ready} onChange={importFile}/></label><details><summary>Supported file format</summary><p>Columns: Date, Description, Amount, with negative amounts for money out and positive for money in. Separate Debit and Credit columns also work. Dates: YYYY-MM-DD or MM/DD/YYYY. PDF and scanned statements are not supported yet. Common transfer descriptions are excluded, but review for transfers and credit-card payments to avoid counting money twice.</p></details>{message&&<p role="status">{message}</p>}{suggestions.length>0&&<div className="current-review"><h3>Review recurring suggestions</h3><p className="help">Nothing is selected automatically. Dates are estimated from past payments; confirm each schedule after importing.</p>{suggestions.map(s=><label className="current-suggestion" key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(prev=>e.target.checked?[...prev,s.id]:prev.filter(id=>id!==s.id))}/><span><b>{s.name}</b><small>{frequencies[s.frequency??'monthly']} · {labels[s.kind]}</small><small>{s.reason}</small></span><strong>{money(s.amount)}</strong></label>)}<button className="button primary" disabled={!selected.length} onClick={importSelected}>Add {selected.length} selected items</button><button className="text-button" onClick={()=>{setSuggestions([]);setSelected([]);setMessage('Import dismissed. No items added.')}}>Dismiss</button></div>}</section>
 <div className="flow-editor">{kinds.map(kind=><section className="glass category-panel" key={kind}><div className="panel-heading"><h2>{labels[kind]}</h2><button className="text-button" disabled={!ready} onClick={()=>add(kind)} aria-label={'Add '+labels[kind]}><Plus size={17}/> Add</button></div><p className="help">{hints[kind]}</p>{items.filter(i=>i.kind===kind).map(i=>{const payday=kind==='saving'&&i.mode&&i.mode!=='scheduled';return <div className="current-item" key={i.id}><div className="current-item-title"><label className="text-field">Name<input value={i.name} maxLength={60} onChange={e=>update(i.id,{name:e.target.value})}/></label><button className="icon-button" aria-label={'Delete '+i.name} onClick={()=>setItems(prev=>prev.filter(x=>x.id!==i.id))}><Trash2 size={18}/></button></div>{kind==='saving'&&<Choice label="How to set it aside" value={i.mode??'scheduled'} onChange={mode=>update(i.id,{mode:mode as FlowItem['mode'],amount:0,incomeId:income[0]?.id})} options={[["scheduled","On its own schedule"],["payday-amount","An amount each payday"],["payday-percent","A percentage each payday"]]}/>}<div className="current-item-grid"><Field label={i.mode==='payday-percent'?'Percent of take-home pay':'Amount each time'} value={i.amount} step={.01} max={i.mode==='payday-percent'?100:1e8} suffix={i.mode==='payday-percent'?'%':'$'} onChange={amount=>update(i.id,{amount})}/>{payday?<Choice label="Linked paycheck" value={i.incomeId??''} onChange={incomeId=>update(i.id,{incomeId})} options={[["","Choose income"],...income.map(x=>[x.id,x.name] as [string,string])]}/>:<Choice label="How often" value={i.frequency??'monthly'} onChange={frequency=>update(i.id,{frequency:frequency as Frequency})} options={Object.entries(frequencies) as [string,string][]}/>}</div>{!payday&&<div className="current-item-grid"><label className="text-field">{kind==='income'?'Next payday':kind==='variable'?'Next allowance date':'Next payment date'}<input type="date" value={i.date??''} onChange={e=>update(i.id,{date:e.target.value})} onBlur={e=>update(i.id,{date:e.target.value})}/></label>{i.frequency==='semimonthly'&&<Field label="Second day of the month" value={i.secondDay??15} min={1} max={31} onChange={secondDay=>update(i.id,{secondDay})}/>}</div>}{i.frequency==='semimonthly'&&i.date&&Number(i.date.slice(-2))===(i.secondDay??15)&&<p className="notice">Choose two different days of the month.</p>}<p className="help">{i.frequency==='once'&&!payday?'One-time amount; excluded from recurring averages.':`${money(monthlyAmount(i,items))} per month on average.`}{!payday&&i.frequency==='semimonthly'?' The first day comes from your date above.':''}{!payday&&['monthly','yearly','semimonthly'].includes(i.frequency??'monthly')?' Dates beyond a month’s end fall on its last day.':''}</p></div>})}{!items.some(i=>i.kind===kind)&&<p className="current-empty">Add your first {kind==='income'?'paycheck':kind==='saving'?'savings plan':'category'}.</p>}</section>)}</div>
 <div className="insight"><Waves/><p>{f.income?`${f.savingsRate.toFixed(1)}% of your average take-home income goes toward savings and investments. Fixed bills use ${f.fixedRate.toFixed(1)}%.`:'Start with your take-home pay. Then give your bills and savings their own schedules.'}</p></div><p className="fine">Planning estimates, not a live bank balance. Include only savings not already deducted from your take-home pay. Amounts can change; review your plan regularly.</p><div className="actions"><Link className="button primary" href={`/calculators/compound-interest#monthly=${Math.max(0,f.remaining)}`}>Explore your monthly room to grow <ArrowUpRight size={18}/></Link><Link className="button glass-button" href="/islands">Give your savings a destination</Link></div></main>
}
